### ISSUE TITLE
Description événement (états)

### ISSUE THREAD

**Issue by EliseV** [caradojo/AgileGrenoble#21]
Ajouter la description de l'évènement en haut du site, juste après "la 10ème édition" : L'agilité dans tous ses états
   L'agilité au jour le jour : du concret , des outils, des pratiques
   Souvenirs de voyages en Agilité
   Un nouveau souffle pour votre agilité

**Comment by bucuri** [comment]
Ajouter un bouton sur la page "billeterie" avec une image qui va bien.
