### ISSUE TITLE
orateurs "spécial 10ème edition"

### ISSUE THREAD

**Issue by EliseV** [caradojo/AgileGrenoble#28]
Ce ne sont pas tous les orateurs
Pour avoir le lien vers tous les orateurs : https://agilegrenoble2017.sched.com/directory/speakers

**Comment by dchipan** [comment]
J'ai ajouté un lien "Voir tous les orateurs" pointant vers SCHED et j'ai laissé le titre de section "Orateurs" pour rester cohérent avec le menu
